steps:
- name: 'gcr.io/cloud-builders/docker'
args:
- 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/trade-app'
  - '.'

  - name: 'gcr.io/cloud-builders/docker'
args:
- 'push'
  - 'gcr.io/$PROJECT_ID/trade-app'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
entrypoint: 'gcloud'
args:
- 'run'
  - 'deploy'
  - 'trade-app'
  - '--image'
  - 'gcr.io/$PROJECT_ID/trade-app'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--set-env-vars'
  - 'ALPACA_API_KEY=${_ALPACA_API_KEY},ALPACA_SECRET_KEY=${_ALPACA_SECRET_KEY},ALPACA_BASE_URL=${_ALPACA_BASE_URL}'

images:
- 'gcr.io/$PROJECT_ID/trade-app'
