steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--platform"
      - "linux/amd64"
      - "-t"
      - "gcr.io/${PROJECT_ID}/trade-app"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/${PROJECT_ID}/trade-app"

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "trade-app"
      - "--image=gcr.io/${PROJECT_ID}/trade-app"
      - "--region=us-west1"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--update-secrets=ALPACA_API_KEY=alpaca-api-key:latest,ALPACA_SECRET_KEY=alpaca-secret-key:latest"
      - "--set-env-vars=ALPACA_BASE_URL=https://api.alpaca.markets"

images:
  - "gcr.io/${PROJECT_ID}/trade-app"
